In [ ]:
#Experiment-1 : Apply Dimensionality Reduction algorithm – PCA and LDA on chosen dataset and perform comparative Analysis of the same.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn import metrics

In [2]:
#Taking the Irish Dataset
iris_df = sns.load_dataset('iris')
iris_df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [3]:
iris_df.tail()

,sepal_length,sepal_width,petal_length,petal_width,species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica


In [4]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
iris_df.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [6]:
iris_df.shape

(150, 5)

In [7]:
iris_df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [8]:
df = iris_df.dropna()

In [10]:
#Selecting features

x = iris_df.drop(columns=['species'])   #Features
y = iris_df['species']                  #Target
print("Training column is:\n",x.head())
print("\nTarget is:\n",y.head())

Training column is:
    sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

Target is:
 0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object


In [33]:
#Spliting Data

x_train , x_test , y_train , y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(x_test.shape)

(120, 4)
(30, 4)


In [34]:
#Normalizing the features

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)
print(x_train_scaled)
print('\n',x_test_scaled.shape)

[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]
 [-1.23014297  0.75647855 -1.2187007  -1.31260282]
 [-1.7177306   0.30929911 -1.39061772 -1.31260282]
 [ 0.59831066 -1.25582892  0.72969227  0.95664273]
 [ 0.72020757  0.30929911  0.44316389  0.4227026 ]
 [-0.74255534  0.98006827 -1.27600637 -1.31260282]
 [-0.98634915  1.20365799 -1.33331205 -1.31260282]
 [-0.74255534  2.32160658 -1.27600637 -1.44608785]
 [-0.01117388 -0.80864948  0.78699794  0.95664273]
 [ 0.23261993  0.75647855  0.44316389  0.55618763]
 [ 1.08589829  0.08570939  0.55777524  0.4227026 ]
 [-0.49876152  1.87442714 -1.39061772 -1.04563275]
 [-0.49876152  1.4272477  -1.27600637 -1.31260282]
 [-0.37686461 -1.47941864 -0.01528151 -0.24472256]
 [ 0.59831066 -0.58505976  0.78699794  0.4227026 ]
 [ 0.72020757  0.08570939  1.01622064  0.8231577 ]
 [ 0.96400139 -0.13788033  0.38585821  0.28921757]
 [ 1.69538284  1.20365799  1.36

In [35]:
#Training Raw data

clf = RandomForestClassifier(n_estimators=100,random_state=42)
clf.fit(x_train_scaled, y_train)
y_pred = clf.predict(x_test_scaled)
print("Accuracy on Raw Data: ",metrics.accuracy_score(y_test, y_pred))

Accuracy on Raw Data:  0.9666666666666667


In [36]:
#Applying PCA

pca = PCA(n_components=2)
x_train_pca = pca.fit_transform(x_train_scaled)
x_test_pca = pca.transform(x_test_scaled)

In [46]:
clf_pca = RandomForestClassifier(n_estimators=100,random_state=42)
clf_pca.fit(x_train_pca, y_train)
y_pred_pca2 = clf_pca.predict(x_test_pca)
print("Accuracy with PCA: ",metrics.accuracy_score(y_test, y_pred_pca2))

Accuracy with PCA:  0.9333333333333333


In [42]:
pca = PCA(n_components=3)
x_train_pca = pca.fit_transform(x_train_scaled)
x_test_pca = pca.transform(x_test_scaled)

In [47]:
clf_pca = RandomForestClassifier(n_estimators=100,random_state=42)
clf_pca.fit(x_train_pca, y_train)
y_pred_pca3 = clf_pca.predict(x_test_pca)
print("Accuracy with PCA: ",metrics.accuracy_score(y_test, y_pred_pca3))

Accuracy with PCA:  0.9333333333333333


In [48]:
print("Accuracy of all :\n")
print("Accuracy on Raw Data:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy with PCA (2 components): ",metrics.accuracy_score(y_test, y_pred_pca2))
print("Accuracy with PCA (3 components): ",metrics.accuracy_score(y_test, y_pred_pca3))

Accuracy of all :

Accuracy on Raw Data: 0.9666666666666667
Accuracy with PCA (2 components):  0.9333333333333333
Accuracy with PCA (3 components):  0.9333333333333333


In [49]:
#Loading Taxis Dataset

taxis_df = sns.load_dataset('taxis')
taxis_df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan


In [50]:
taxis_df.tail()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn


In [51]:
taxis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64         
 3   distance         6433 non-null   float64       
 4   fare             6433 non-null   float64       
 5   tip              6433 non-null   float64       
 6   tolls            6433 non-null   float64       
 7   total            6433 non-null   float64       
 8   color            6433 non-null   object        
 9   payment          6389 non-null   object        
 10  pickup_zone      6407 non-null   object        
 11  dropoff_zone     6388 non-null   object        
 12  pickup_borough   6407 non-null   object        
 13  dropoff_borough  6388 non-null   object        
dtypes: datetime64[ns](2), float64(5), int64(

In [52]:
taxis_df.shape

(6433, 14)

In [53]:
taxis_df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [54]:
df = taxis_df.dropna()

In [55]:
#Converting Target Variable to Numerical

le = LabelEncoder()
taxis_df['payment'] = le.fit_transform(taxis_df['payment'])

In [56]:
#Selecting Features

x = taxis_df[['fare','distance','pickup_borough','dropoff_borough']]
x = pd.get_dummies(x, drop_first=True)
y = taxis_df['payment']

In [57]:
x_train , x_test , y_train , y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [58]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [59]:
clf = RandomForestClassifier(n_estimators=100,random_state=42)
clf.fit(x_train_scaled, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [60]:
y_pred = clf.predict(x_test_scaled)
print("Accuracy on Raw Data:",metrics.accuracy_score(y_test,y_pred))

Accuracy on Raw Data: 0.6386946386946387


In [61]:
pca = PCA(n_components=2)
x_train_pca = pca.fit_transform(x_train_scaled)
x_test_pca = pca.transform(x_test_scaled)

In [62]:
clf_pca = RandomForestClassifier(n_estimators=100,random_state=42)
clf_pca.fit(x_train_pca,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [63]:
y_pred_pca2 = clf_pca.predict(x_test_pca)
print("Accuracy with PCS (2 components): ",metrics.accuracy_score(y_test,y_pred_pca2))

Accuracy with PCS (2 components):  0.6643356643356644


In [64]:
pca = PCA(n_components=3)
x_train_pca = pca.fit_transform(x_train_scaled)
x_test_pca = pca.transform(x_test_scaled)

In [65]:
clf_pca = RandomForestClassifier(n_estimators=100,random_state=42)
clf_pca.fit(x_train_pca,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [66]:
y_pred_pca3 = clf_pca.predict(x_test_pca)
print("Accuracy with PCS (3 components): ",metrics.accuracy_score(y_test,y_pred_pca3))

Accuracy with PCS (3 components):  0.6837606837606838


In [67]:
print("Accuracy on Raw Data:",metrics.accuracy_score(y_test,y_pred))
print("Accuracy with PCS (2 components): ",metrics.accuracy_score(y_test,y_pred_pca2))
print("Accuracy with PCS (3 components): ",metrics.accuracy_score(y_test,y_pred_pca3))

Accuracy on Raw Data: 0.6386946386946387
Accuracy with PCS (2 components):  0.6643356643356644
Accuracy with PCS (3 components):  0.6837606837606838
